### PR TITLE
Add gallery

### LINKED ISSUE #42: Add a gallery showing diagram examples

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #42

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

### CODE REVIEW

**Comment by rschnekenbu** [comment]
Is there an easy way to fix the layout for the UML examples in the gallery example selection part? There is some text overlap 
layoutissue

**Comment by JonasHelming** [comment]
> @JonasHelming Is there an easy way to fix the layout for the UML examples in the gallery example selection part? There is some text overlap layoutissue

Yes, the GIFs have to be much wider and less high. There is a maximum height, if that is reached, the items does not grap more space, hence the overlapping text

**Comment by rschnekenbu** [comment]
use case diagram and class diagram gif update, no more layout issues.

**Review by planger — APPROVED** [review]
Thanks, looks great!
I may re-order them at some point, but for now I think it is great.

**Pull request merged**
