### PR TITLE
Update diagram GIF to new style

### PR DESCRIPTION
**Pull request by planger**

### CODE REVIEW

**Comment by tortmayr** [comment]
Thanks looks good to me. However, I'm not sure if  we really should use the dark theme for the new animated GIF. The old one was recorded in light theme which IMO fits better into the overall design of the webpage. In addition, the dark theme gif might look a bit out of place when used in the Github READMEs.

**Comment by planger** [comment]
Thanks for fast reply! I received exactly the opposite feedback... ie to switch to more dark-themed GIFs. :-)

I don't have a very strong opinion on that, but I tend to prefer the dark ones, especially on the website where the background is dark gray.

Just as a context, I'm currently also working on making some adjustments on the website, at least the gallery and the landing page (see work in progress below). With that, dark looks imho better too. WDYT?

image

**Comment by tortmayr** [comment]
I agree with the proposed changes the dark one definitively fits in better.
I personally don't have a strong opinion on that either and just wanted to raise the topic one more.
However, when we then should make sure that we also use dark theme when we upgrade the gifs/mpegs for the integration repositories.

**Review by tortmayr — APPROVED** [review]

**Comment by planger** [comment]
Ok thanks! We can always switch back, if we ever feel it fits better.

**Pull request merged**
